/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diaginfo_wr;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 007
 */
public class GUI extends javax.swing.JFrame {
  private static Connection Conexion;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jFrame2.setVisible(true);
        jFrame2.setLocation(200,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        qr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NoParte = new javax.swing.JLabel();
        Oracle = new javax.swing.JLabel();
        Proveedor = new javax.swing.JLabel();
        Celula = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        noparte = new javax.swing.JTextField();
        oracle = new javax.swing.JTextField();
        proveedor = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        Precio_r = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Precio1 = new javax.swing.JLabel();
        Precio_r1 = new javax.swing.JTextField();
        Precio2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jFrame2.setMinimumSize(new java.awt.Dimension(469, 338));
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jFrame2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Informacion del Servidor");
        jFrame2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jButton2.setText("CONECTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaginfo_wr/allegion.png"))); // NOI18N
        jFrame2.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaginfo_wr/allegion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Facilitador");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 40));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setAutoscrolls(false);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 340, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Diagnosis Method");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, -1, 40));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 340, 100));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Comments");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 570, -1, 30));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setAutoscrolls(false);
        jScrollPane6.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 340, 90));

        qr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(qr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 40));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 110, 50));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 110, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 20, 760));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 22, 20, 700));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Failure Mode");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("QR CODE");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        NoParte.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        NoParte.setText("Part Number:");
        getContentPane().add(NoParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        Oracle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Oracle.setText("ORACLE:");
        getContentPane().add(Oracle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        Proveedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Proveedor.setText("Suplieer:");
        getContentPane().add(Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        Celula.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Celula.setText("Cell:");
        getContentPane().add(Celula, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 60, -1));

        Precio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Precio.setText("Secuence Name:");
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        Descripcion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Descripcion.setText("Description:");
        getContentPane().add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Test description");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, 40));

        jTextField2.setText("Roberto Corona");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 180, -1));

        noparte.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        noparte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noparteActionPerformed(evt);
            }
        });
        getContentPane().add(noparte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 180, -1));

        oracle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(oracle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 190, 40));

        proveedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 210, 40));

        descripcion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 230, -1));

        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 180, 40));

        Precio_r.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Precio_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 180, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Specifications");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, -1, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 330, -1));

        Precio1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Precio1.setText("Price:");
        getContentPane().add(Precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        Precio_r1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Precio_r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_r1ActionPerformed(evt);
            }
        });
        getContentPane().add(Precio_r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 180, 40));

        Precio2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Precio2.setText("Failure Date:");
        getContentPane().add(Precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 340, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            MySQLConnection("root","","tuto");      // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
getValues("nombres");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DELETE("NOMBRES");  
insertData("NOMBRES", qr.getText(), noparte.getText(), oracle.getText() , proveedor.getText(),jTextArea2.getText(),jTextArea3.getText(),jTextArea5.getText(),descripcion.getText(),jTextArea6.getText(),jTextField2.getText(),Precio_r.getText(),jTextField1.getText(),jTextArea1.getText());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void noparteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noparteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noparteActionPerformed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void Precio_r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_r1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celula;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel NoParte;
    private javax.swing.JLabel Oracle;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Precio1;
    private javax.swing.JLabel Precio2;
    private javax.swing.JTextField Precio_r;
    private javax.swing.JTextField Precio_r1;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField noparte;
    private javax.swing.JTextField oracle;
    private javax.swing.JTextField proveedor;
    private javax.swing.JTextField qr;
    // End of variables declaration//GEN-END:variables

public void closeConnection() {
        try {
            Conexion.close();
            JOptionPane.showMessageDialog(null, "Se ha finalizado la conexión con el servidor");
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
public void MySQLConnection(String user, String pass, String db_name) throws Exception {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Conexion = DriverManager.getConnection("jdbc:mysql://192.168.107:3306/"+db_name, user, pass);
            JOptionPane.showMessageDialog(null, "Se ha iniciado la conexión con el servidor de forma exitosa");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public void DELETE(String TABLE)  {
      String Query = "DELETE FROM nombres WHERE ID="+"'"+qr.getText()+"'";
        Statement st = null;
      try {
          st = Conexion.createStatement();
      } catch (SQLException ex) {
          Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
      }
      try {
          st.executeUpdate(Query);
      } catch (SQLException ex) {
          Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
      }
    }

 


 public void insertData(String table_name, String ID, String partNumber, String ORACLE , String proveedor, String Descripcion_prueba,String MetodoDiag,String SPEC,String Descripcion,String Modo_falla,String facilitador,String precio,String celulas,String comentarios) {
        try {
            String Query = "INSERT INTO " + table_name + " VALUES("
                    + "\"" + ID + "\", "
                    + "\"" + partNumber + "\", "
                    + "\"" + ORACLE + "\", "
                    + "\"" + proveedor + "\", "
                    + "\"" + Descripcion_prueba+ "\","
                    + "\"" + MetodoDiag + "\","
                    + "\"" + SPEC+ "\","
                    + "\"" + Descripcion+ "\","
                    + "\"" + Modo_falla+ "\","
             + "\"" + facilitador+ "\","
                     + "\"" + precio+ "\","
                       + "\"" + comentarios+ "\","
                    + "\"" + celulas+ "\")";
            Statement st = Conexion.createStatement();
            st.executeUpdate(Query);
            JOptionPane.showMessageDialog(null, "Datos almacenados de forma exitosa");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en el almacenamiento de datos"+ex);
        }
    }
 
 

 public void getValues(String table_name) {
        try {
            String Query = "SELECT * FROM " + table_name;
            Statement st = Conexion.createStatement();
            java.sql.ResultSet resultSet;
          
        
           resultSet = st.executeQuery(Query);
      

           
            while (resultSet.next()) {
                if(qr.getText().equals(resultSet.getString("ID"))){
                    System.out.println("ID: " + resultSet.getString("ID") + " "
                      + "PartNumber: " + resultSet.getString("partNumber") + " " + resultSet.getString("ORACLE") + " "
                       + "proveedor: " + resultSet.getString("proveedor") + " "
                       + "Descripcion: " + resultSet.getString("Descripcion"));
                    
              noparte.setText(resultSet.getString("partNumber"));
              descripcion.setText(resultSet.getString("Descripcion"));
              oracle.setText(resultSet.getString("ORACLE"));
              proveedor.setText(resultSet.getString("proveedor") );
              jTextArea2.setText(resultSet.getString("Descripcion_prueba"));
              jTextArea6.setText(resultSet.getString("Modo_falla"));
              jTextArea3.setText(resultSet.getString("MetodoDiag"));
              jTextArea5.setText(resultSet.getString("SPEC"));
              jTextField2.setText(resultSet.getString("facilitador"));
              jTextField1.setText(resultSet.getString("celulas"));
              Precio_r.setText(resultSet.getString("precio"));
              jTextArea1.setText(resultSet.getString("comentarios"));
                }
                      
             
               
           }
 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la adquisición de datos");
        }
    }
}
